### ISSUE TITLE
Fatal error: elmo_motor.h: No such file or directory

### ISSUE THREAD

**Issue by Zoschen** [york-fu/elmo_driver#1]
Hello there,
I've been trying to run your example on my Elmo drive but the example code won't compile because it can't find the elmo_motor.h header file.

![Screenshot from 2023-08-28 08-34-27](https://github.com/york-fu/elmo_driver/assets/64479808/6b4512ac-a0e2-4ab2-a5ac-01e7bc362568)

I tried to edit the CMakeLists files but got into more problems. 
Could you help me solving this problem?

**Comment by york-fu** [comment]
Link library error, resolved, please pull the latest commit.
